language: dart
dart:
  - stable
script:
  - pub run test
  - pub run dart_codecov_generator --report-on=lib/ --no-html --verbose
  - bash <(curl -s https://codecov.io/bash)
  - ./tool/analyze.sh
  - ./tool/dartfmt.sh -e