language: dart
dart:
  - stable
script:
  - pub run test
  - pub run dart_codecov_generator:generate_coverage --report-on=lib/ --no-html --verbose
  - pub run dart_codecov coverage.lcov
  - pub run dart_style:format -n lib test