language: dart

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

jobs:
  include:
    - dart: 2.3.0
      name: "SDK: 2.3.0"
      script:
        - dartanalyzer .
        - pub run test
    - dart: stable
      name: "SDK: stable"
      script:
        - dartanalyzer .
        - dartfmt -n --set-exit-if-changed .
        - pub run dependency_validator
        - pub run test
    - dart: dev
      name: "SDK: dev"
      script:
        - dartanalyzer .
        - pub run test
