language: dart
dart:
  - stable
script:
  - pub run test
  - pub run dart_codecov_generator --report-on=lib/ --no-html --verbose
  - pub run dart_codecov coverage.lcov
  - ./tool/analyze.sh
  - ./tool/dartfmt.sh -e