language: dart

dart:
  - 1.24.3
  - 2.0.0

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

script:
- dartfmt --set-exit-if-changed -w .
- dartanalyzer lib test
- pub run dependency_validator -i coverage
- pub run test
