name: fluri
version: 1.2.3
description: Fluri is a fluent URI library built to make URI mutation easy.
authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Dustin Lessard <evan.weible@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Jay Udey <jay.udey@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
homepage: https://github.com/Workiva/fluri
dev_dependencies:
  coverage: ^0.10.0
  dart_dev: ^1.9.2
  dart_style: ^1.0.6
  dependency_validator: ^1.1.2
  test: ^0.12.23+1
environment:
  sdk: ">=1.23.0 <2.0.0"
