name: fluri
version: 0.0.0
description: 'Fluri is a fluent URI library built to make URI mutation easy'
authors:
  - Workiva Client Platform Team <team-clientplatform@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
documentation:
homepage: https://github.com/Workiva/fluri
dev_dependencies:
  test: 0.12.0-rc.0