name: fluri
version: 1.0.0
description: 'Fluri is a fluent URI library built to make URI mutation easy'
authors:
  - Workiva Client Platform Team <team-clientplatform@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
homepage: https://github.com/Workiva/fluri
dev_dependencies:
  dart_style: '>=0.1.8 <0.2.0'
  test: 0.12.0-rc.0
