name: fluri
version: 1.3.0
description: Fluri is a fluent URI library built to make URI mutation easy.
homepage: https://github.com/Workiva/fluri
environment:
  sdk: ">=2.3.0 <3.0.0"
dev_dependencies:
  dependency_validator: ^1.4.0
  test: ^1.9.2
